$ A Globalyzer generated message file

$set MainSet

$  SOURCE_FILE C:/Path/to/my/source/StringBug.hpp
STRI_BADLINE_6 "Bad line"
STRI_INVALID_7 "Invalid Rectangle"
STRI_INVALID_8 "Invalid Color"
STRI_INVALID_9 "Invalid Point"
STRI_INVALID_10 "Invalid DWORD"
STRI_UNRECOG_11 "Unrecognized type"
STRI_SLINEDS_12 "%s (line #%d) : %s"
STRI_RUNTIME_13 "Runtime Variable Error"
STRI_KEYNOTF_14 "Key not found"
123_555_1 "555"
123_777_2 "777"
123_ytyty_3 "ytyty"
123_lkjhg_4 "lkjhg"
123_iuyt_5 "iuyt"
123_2310_1 "2310"
123_2410_2 "2410"
123_2510_3 "2510"
